[workspace]
resolver = "2"
members = ["pkgs/mrlyrs", "pkgs/bridge", "pkgs/mrlypy", "pkgs/mrlyjs/units/*"]
default-members = ["pkgs/mrlyrs"]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/mrlyprod/mrlyprod"

[profile.release]
lto = true
codegen-units = 1
strip = true

[workspace.dependencies]
mrlyrs = { path = "pkgs/mrlyrs" }
