[workspace]
resolver = "2"
members = ["pkgs/mrlyrs", "bridge", "pkgs/mrlypy", "pkgs/mrlyjs/units/*", "figures", "site/demos/logic", "research/lab/rs/*"]
default-members = ["pkgs/mrlyrs", "site/demos/logic"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mrlyprod/mrlyprod"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.fig]
inherits = "release"
lto = false
codegen-units = 16
strip = false

[workspace.dependencies]
demos = { path = "site/demos/logic", version = "0.3.0" }
mrlyrs = { path = "pkgs/mrlyrs", version = "0.2.0" }
ledger = { path = "research/lab/rs/ledger", version = "0.3.0" }
atlas = { path = "research/lab/rs/atlas", version = "0.3.0" }
num-bigint = "0.4"
num-rational = "0.4"
faer = "0.24"
