import * as wasm from "./pkg/core/mrlyjs_core.js";

export { default, initSync } from "./pkg/core/mrlyjs_core.js";
export const Rng = wasm.Rng;
export const Colorizer = wasm.Colorizer;
export const Dtype = wasm.Dtype;
export const HEX_RATIO = wasm.HEX_RATIO;
export const Image = wasm.Image;
export const PNG_MAGIC = wasm.PNG_MAGIC;
export const hex_fit = wasm.hex_fit;
export const hex_size = wasm.hex_size;
export const resample = wasm.resample;
export const unpng = wasm.unpng;
export const cell = {
    anti: wasm.cell_anti,
    binarize: wasm.cell_binarize,
    binarize_otsu: wasm.cell_binarize_otsu,
    blur: wasm.cell_blur,
    color_at: wasm.cell_color_at,
    combine: wasm.cell_combine,
    fractal: wasm.cell_fractal,
    invert: wasm.cell_invert,
    layers: wasm.cell_layers,
    magic: wasm.cell_magic,
    mapping: wasm.cell_mapping,
    merge: wasm.cell_merge,
    moore: wasm.cell_moore,
    mosaic: wasm.cell_mosaic,
    neighbors: wasm.cell_neighbors,
    new: wasm.cell_new,
    new_: wasm.cell_new,
    pad: wasm.cell_pad,
    paint: wasm.cell_paint,
    perforate: wasm.cell_perforate,
    remap: wasm.cell_remap,
    rgba: wasm.cell_rgba,
    rot90_map: wasm.cell_rot90_map,
    rotate: wasm.cell_rotate,
    shape: wasm.cell_shape,
    size: wasm.cell_size,
    tile: wasm.cell_tile,
    tile_map: wasm.cell_tile_map,
};
export const codec = {
    gif: wasm.codec_gif,
    png: wasm.codec_png,
};
export const colors = {
    ALPHA: wasm.colors_ALPHA,
    BLACK: wasm.colors_BLACK,
    BLUE: wasm.colors_BLUE,
    BROWN: wasm.colors_BROWN,
    CYAN: wasm.colors_CYAN,
    DARK: wasm.colors_DARK,
    GRAY: wasm.colors_GRAY,
    GREEN: wasm.colors_GREEN,
    INDIGO: wasm.colors_INDIGO,
    LIGHT: wasm.colors_LIGHT,
    MINT: wasm.colors_MINT,
    NAMES: wasm.colors_NAMES,
    ORANGE: wasm.colors_ORANGE,
    PALETTE: wasm.colors_PALETTE,
    PINK: wasm.colors_PINK,
    PURPLE: wasm.colors_PURPLE,
    RED: wasm.colors_RED,
    TEAL: wasm.colors_TEAL,
    Theme: wasm.colors_Theme,
    WHITE: wasm.colors_WHITE,
    YELLOW: wasm.colors_YELLOW,
    alpha: wasm.colors_alpha,
    board: wasm.colors_board,
    css: wasm.colors_css,
    from_hex: wasm.colors_from_hex,
    gradient: wasm.colors_gradient,
    ink: wasm.colors_ink,
    invert: wasm.colors_invert,
    lightness: wasm.colors_lightness,
    luma_types: wasm.colors_luma_types,
    mix: wasm.colors_mix,
    named: wasm.colors_named,
    random: wasm.colors_random,
    rgb: wasm.colors_rgb,
    rgba: wasm.colors_rgba,
    shades: wasm.colors_shades,
    snap: wasm.colors_snap,
    to_hex: wasm.colors_to_hex,
};
export const error = {
    parse: wasm.error_parse,
};
export const image = {
    blur: wasm.image_blur,
};
export const paint = {
    Edition: wasm.paint_Edition,
    Ink: wasm.paint_Ink,
    Paint: wasm.paint_Paint,
    Scheme: wasm.paint_Scheme,
    Target: wasm.paint_Target,
    apply: wasm.paint_apply,
    coat: wasm.paint_coat,
    paint: wasm.paint_paint,
    prime: wasm.paint_prime,
    random_edition: wasm.paint_random_edition,
    reroll: wasm.paint_reroll,
    setup: wasm.paint_setup,
    tag: wasm.paint_tag,
};
export const ramp = {
    color: wasm.ramp_color,
    colors: wasm.ramp_colors,
};
export const rng = {
    below: wasm.rng_below_,
    boolean: wasm.rng_boolean_,
    chance: wasm.rng_chance_,
    new: wasm.rng_new_,
    new_: wasm.rng_new_,
    range: wasm.rng_range_,
    sample_indices: wasm.rng_sample_indices_,
    unit: wasm.rng_unit_,
};
export const tensor = {
    at: wasm.tensor_at,
    binarize: wasm.tensor_binarize,
    binarize_otsu: wasm.tensor_binarize_otsu,
    blur: wasm.tensor_blur,
    bytes: wasm.tensor_bytes,
    count: wasm.tensor_count,
    dtype: wasm.tensor_dtype,
    exposed: wasm.tensor_exposed,
    filled: wasm.tensor_filled,
    flip: wasm.tensor_flip,
    fractal: wasm.tensor_fractal,
    full: wasm.tensor_full,
    get: wasm.tensor_get,
    i32: wasm.tensor_i32,
    i32s: wasm.tensor_i32s,
    index: wasm.tensor_index,
    invert: wasm.tensor_invert,
    kron: wasm.tensor_kron,
    layers: wasm.tensor_layers,
    neighbors: wasm.tensor_neighbors,
    new: wasm.tensor_new,
    new_: wasm.tensor_new,
    of: wasm.tensor_of,
    otsu_threshold: wasm.tensor_otsu_threshold,
    pad: wasm.tensor_pad,
    perforate: wasm.tensor_perforate,
    put: wasm.tensor_put,
    rot90: wasm.tensor_rot90,
    set: wasm.tensor_set,
    size: wasm.tensor_size,
    slice: wasm.tensor_slice,
    sum: wasm.tensor_sum,
    tile: wasm.tensor_tile,
    transpose: wasm.tensor_transpose,
    typed: wasm.tensor_typed,
    u16: wasm.tensor_u16,
    u16s: wasm.tensor_u16s,
    u32: wasm.tensor_u32,
    u32s: wasm.tensor_u32s,
    u8: wasm.tensor_u8,
};
