import * as wasm from "./pkg/math/mrlyjs_math.js";

export { default, initSync } from "./pkg/math/mrlyjs_math.js";
export const Rng = wasm.Rng;
export const atoms = {
    carpet_2d: wasm.atoms_carpet_2d,
    carpet_3d: wasm.atoms_carpet_3d,
    carpet_nd: wasm.atoms_carpet_nd,
    dust_2d: wasm.atoms_dust_2d,
    dust_3d: wasm.atoms_dust_3d,
    dust_nd: wasm.atoms_dust_nd,
    hline_2d: wasm.atoms_hline_2d,
    htree_2d: wasm.atoms_htree_2d,
    line_nd: wasm.atoms_line_nd,
    net_2d: wasm.atoms_net_2d,
    net_3d: wasm.atoms_net_3d,
    net_nd: wasm.atoms_net_nd,
    noise_2d: wasm.atoms_noise_2d,
    noise_3d: wasm.atoms_noise_3d,
    ones_2d: wasm.atoms_ones_2d,
    ones_3d: wasm.atoms_ones_3d,
    point_2d: wasm.atoms_point_2d,
    point_3d: wasm.atoms_point_3d,
    point_nd: wasm.atoms_point_nd,
    star_2d: wasm.atoms_star_2d,
    star_3d: wasm.atoms_star_3d,
    star_nd: wasm.atoms_star_nd,
    tree_nd: wasm.atoms_tree_nd,
    vline_2d: wasm.atoms_vline_2d,
    void_2d: wasm.atoms_void_2d,
    void_3d: wasm.atoms_void_3d,
    void_nd: wasm.atoms_void_nd,
    vtree_2d: wasm.atoms_vtree_2d,
    xline_3d: wasm.atoms_xline_3d,
    xtree_3d: wasm.atoms_xtree_3d,
    yline_3d: wasm.atoms_yline_3d,
    ytree_3d: wasm.atoms_ytree_3d,
    zeros_2d: wasm.atoms_zeros_2d,
    zeros_3d: wasm.atoms_zeros_3d,
    zline_3d: wasm.atoms_zline_3d,
    ztree_3d: wasm.atoms_ztree_3d,
};
export const bang = {
    Design: wasm.bang_Design,
    MagicLayer: wasm.bang_MagicLayer,
    Universe: wasm.bang_Universe,
    bang: wasm.bang_bang,
    code_to_corners: wasm.bang_code_to_corners,
    corners: wasm.bang_corners,
    corners_to_code: wasm.bang_corners_to_code,
    levels_code: wasm.bang_levels_code,
    magic: wasm.bang_magic,
    magic_named: wasm.bang_magic_named,
    sources: wasm.bang_sources,
    symmetries: wasm.bang_symmetries,
    total_exposure: wasm.bang_total_exposure,
    touches_every_corner: wasm.bang_touches_every_corner,
    universe_codes: wasm.bang_universe_codes,
    baseq: {
        WALK_LIMIT: wasm.bang_baseq_WALK_LIMIT,
        axis_maps: wasm.bang_baseq_axis_maps,
        bracelets: wasm.bang_baseq_bracelets,
        canonical: wasm.bang_baseq_canonical,
        carry: wasm.bang_baseq_carry,
        class_sequence: wasm.bang_baseq_class_sequence,
        classes: wasm.bang_baseq_classes,
        distinct_designs: wasm.bang_baseq_distinct_designs,
        even_fill_is_balanced: wasm.bang_baseq_even_fill_is_balanced,
        fill_from_corners: wasm.bang_baseq_fill_from_corners,
        group: wasm.bang_baseq_group,
        group_order: wasm.bang_baseq_group_order,
        orbit: wasm.bang_baseq_orbit,
        predicted_group_order: wasm.bang_baseq_predicted_group_order,
        representatives: wasm.bang_baseq_representatives,
        sequence: wasm.bang_baseq_sequence,
        total_designs: wasm.bang_baseq_total_designs,
    },
    catalog: {
        ANTIS_2D: wasm.bang_catalog_ANTIS_2D,
        ANTIS_3D: wasm.bang_catalog_ANTIS_3D,
        antis: wasm.bang_catalog_antis,
    },
    code: {
        get: wasm.bang_code_get,
    },
    factory: {
        create: wasm.bang_factory_create,
        create_from_corners: wasm.bang_factory_create_from_corners,
        create_named: wasm.bang_factory_create_named,
        residue_corners: wasm.bang_factory_residue_corners,
        total_codes: wasm.bang_factory_total_codes,
    },
    universe: {
        anf: wasm.bang_universe_anf,
        anf_string: wasm.bang_universe_anf_string,
        apply: wasm.bang_universe_apply,
        corner_index: wasm.bang_universe_corner_index,
        degree: wasm.bang_universe_degree,
        orbit: wasm.bang_universe_orbit,
        permutations: wasm.bang_universe_permutations,
    },
    word: {
        Schedule: wasm.bang_word_Schedule,
        components: wasm.bang_word_components,
        constant_functional: wasm.bang_word_constant_functional,
        dimension: wasm.bang_word_dimension,
        fill: wasm.bang_word_fill,
        fills: wasm.bang_word_fills,
        letter: wasm.bang_word_letter,
        native: wasm.bang_word_native,
        period: wasm.bang_word_period,
        prefixes: wasm.bang_word_prefixes,
        rates: wasm.bang_word_rates,
        side: wasm.bang_word_side,
        spell: wasm.bang_word_spell,
        staircase: wasm.bang_word_staircase,
        thue_morse: wasm.bang_word_thue_morse,
    },
};
export const cell = {
    grow: wasm.cell_grow,
    paint: wasm.cell_paint,
    census: {
        edges: wasm.cell_census_edges,
        exposure: wasm.cell_census_exposure,
        fills: wasm.cell_census_fills,
        vertices: wasm.cell_census_vertices,
        voids: wasm.cell_census_voids,
    },
    geometry: {
        merge_reps: wasm.cell_geometry_merge_reps,
        perforate: wasm.cell_geometry_perforate,
    },
    models: {
        anti: wasm.cell_models_anti,
        binarize: wasm.cell_models_binarize,
        binarize_otsu: wasm.cell_models_binarize_otsu,
        blur: wasm.cell_models_blur,
        combine: wasm.cell_models_combine,
        counting_dtype: wasm.cell_models_counting_dtype,
        depth: wasm.cell_models_depth,
        dtype_for: wasm.cell_models_dtype_for,
        fractal: wasm.cell_models_fractal,
        height: wasm.cell_models_height,
        invert: wasm.cell_models_invert,
        layers: wasm.cell_models_layers,
        neighbors: wasm.cell_models_neighbors,
        new: wasm.cell_models_new,
        new_: wasm.cell_models_new,
        orient: wasm.cell_models_orient,
        pad: wasm.cell_models_pad,
        paint: wasm.cell_models_paint,
        perforate: wasm.cell_models_perforate,
        rotate: wasm.cell_models_rotate,
        tile: wasm.cell_models_tile,
        types: wasm.cell_models_types,
        width: wasm.cell_models_width,
    },
    serializer: {
        byte_cube: wasm.cell_serializer_byte_cube,
        byte_grid: wasm.cell_serializer_byte_grid,
        color_grid: wasm.cell_serializer_color_grid,
        count_cube: wasm.cell_serializer_count_cube,
        count_grid: wasm.cell_serializer_count_grid,
        parse: wasm.cell_serializer_parse,
        tag_layer: wasm.cell_serializer_tag_layer,
        types_field: wasm.cell_serializer_types_field,
    },
};
export const counts = {
    Exposure: wasm.counts_Exposure,
    centered_hexagonal: wasm.counts_centered_hexagonal,
    cut_fills: wasm.counts_cut_fills,
    cut_voids: wasm.counts_cut_voids,
    dimension: wasm.counts_dimension,
    edges_of_tile: wasm.counts_edges_of_tile,
    exposure: wasm.counts_exposure,
    exposure_of_tile: wasm.counts_exposure_of_tile_,
    exposure_recurrence: wasm.counts_exposure_recurrence_,
    fill: wasm.counts_fill,
    fill_from_corners: wasm.counts_fill_from_corners,
    grid: wasm.counts_grid,
    limit: wasm.counts_limit,
    pairs: wasm.counts_pairs,
    positions: wasm.counts_positions,
    pro_fills: wasm.counts_pro_fills,
    pro_voids: wasm.counts_pro_voids,
    profile_of_tile: wasm.counts_profile_of_tile,
    ratio: wasm.counts_ratio,
    rational: wasm.counts_rational,
    surface: wasm.counts_surface,
    void: wasm.counts_void,
    void_: wasm.counts_void,
    diagonal: {
        WIDEST: wasm.counts_diagonal_WIDEST,
    },
    ladder: {
        cap: wasm.counts_ladder_cap,
        carry_matrix: wasm.counts_ladder_carry_matrix,
        characteristic: wasm.counts_ladder_characteristic,
        determinant: wasm.counts_ladder_determinant,
        digit_polynomial: wasm.counts_ladder_digit_polynomial,
        even_block: wasm.counts_ladder_even_block,
        fill: wasm.counts_ladder_fill,
        ladder: wasm.counts_ladder_ladder,
        perron: wasm.counts_ladder_perron,
        sign: wasm.counts_ladder_sign,
        spectral_ratio: wasm.counts_ladder_spectral_ratio,
        trace: wasm.counts_ladder_trace,
    },
    six: {
        grid_triangles: wasm.counts_six_grid_triangles,
        solid_slice_boundary: wasm.counts_six_solid_slice_boundary,
        solid_slice_core_edges: wasm.counts_six_solid_slice_core_edges,
        solid_slice_core_nodes: wasm.counts_six_solid_slice_core_nodes,
        solid_slice_edges: wasm.counts_six_solid_slice_edges,
        solid_slice_interior: wasm.counts_six_solid_slice_interior,
        solid_slice_triangles: wasm.counts_six_solid_slice_triangles,
        solid_slice_vertices: wasm.counts_six_solid_slice_vertices,
    },
};
export const graph = {
    Layout: wasm.graph_Layout,
    Network: wasm.graph_Network,
    census: wasm.graph_census,
    components: wasm.graph_components,
    core_graph: wasm.graph_core_graph,
    edge_graph: wasm.graph_edge_graph,
    fractal_dimension: wasm.graph_fractal_dimension,
    junctions: wasm.graph_junctions,
    largest_component: wasm.graph_largest_component,
    roles: wasm.graph_roles,
    tips: wasm.graph_tips,
    total_length: wasm.graph_total_length,
    tunnel_graph: wasm.graph_tunnel_graph,
};
export const moire = {
    Field: wasm.moire_Field,
    Layer: wasm.moire_Layer,
    Preset: wasm.moire_Preset,
    Spec: wasm.moire_Spec,
    Volume: wasm.moire_Volume,
    all: wasm.moire_all,
    frame: wasm.moire_frame,
    layer: wasm.moire_layer,
    named: wasm.moire_named,
    render: wasm.moire_render,
    stack: wasm.moire_stack,
    stack_codes: wasm.moire_stack_codes,
    volume: wasm.moire_volume,
    pairs: {
        correlation: wasm.moire_pairs_correlation,
        sampled: wasm.moire_pairs_sampled,
        witness: wasm.moire_pairs_witness,
    },
    sample: {
        axes: wasm.moire_sample_axes,
        membership: wasm.moire_sample_membership,
        pack: wasm.moire_sample_pack,
    },
};
export const name = {
    Bang: wasm.name_Bang,
    Lattice: wasm.name_Lattice,
    Sequence: wasm.name_Sequence,
    Word: wasm.name_Word,
};
export const press = {
    CORNERS: wasm.press_CORNERS,
    Press: wasm.press_Press,
    containing: wasm.press_containing,
    coordinates: wasm.press_coordinates,
    count_below: wasm.press_count_below,
    distinct: wasm.press_distinct,
    interleave: wasm.press_interleave,
    layer_table: wasm.press_layer_table,
    member: wasm.press_member,
    members: wasm.press_members,
    profile: wasm.press_profile,
    usage: wasm.press_usage,
    word_count: wasm.press_word_count,
    word_member: wasm.press_word_member,
    word_members: wasm.press_word_members,
    word_profile: wasm.press_word_profile,
};
export const roulette = {
    Nodes: wasm.roulette_Nodes,
    nodes: wasm.roulette_nodes,
    side: wasm.roulette_side,
    spread: wasm.roulette_spread,
};
export const rules = {
    BASE: wasm.rules_BASE,
    render: wasm.rules_render,
    tree_axes: wasm.rules_tree_axes,
};
export const shape = {
    Frac: wasm.shape_Frac,
    REFINE_LIMIT: wasm.shape_REFINE_LIMIT,
    Region: wasm.shape_Region,
    census: wasm.shape_census,
    classify: wasm.shape_classify,
    crop: wasm.shape_crop,
    crossing_shell: wasm.shape_crossing_shell,
    crossing_tree: wasm.shape_crossing_tree,
    named: wasm.shape_named,
    radial_census: wasm.shape_radial_census,
    refine: wasm.shape_refine,
    regions: wasm.shape_regions,
    shapes: wasm.shape_shapes,
};
export const six = {
    FILL: wasm.six_FILL,
    GRID: wasm.six_GRID,
    LEFT: wasm.six_LEFT,
    RIGHT: wasm.six_RIGHT,
    UP: wasm.six_UP,
    VOID: wasm.six_VOID,
    anti: wasm.six_anti,
    binarize: wasm.six_binarize,
    binarize_otsu: wasm.six_binarize_otsu,
    blank: wasm.six_blank,
    blur: wasm.six_blur,
    census: wasm.six_census,
    components: wasm.six_components,
    cut: wasm.six_cut,
    cut_design: wasm.six_cut_design,
    east: wasm.six_east,
    euler: wasm.six_euler,
    fills: wasm.six_fills,
    fills_only: wasm.six_fills_only,
    framed: wasm.six_framed,
    from_json: wasm.six_from_json,
    giant: wasm.six_giant,
    giant_network: wasm.six_giant_network,
    height: wasm.six_height,
    holes: wasm.six_holes,
    is_cube: wasm.six_is_cube,
    is_hex: wasm.six_is_hex,
    iso: wasm.six_iso,
    iso_design: wasm.six_iso_design,
    new: wasm.six_new,
    new_: wasm.six_new,
    north: wasm.six_north,
    orientation: wasm.six_orientation,
    pad: wasm.six_pad,
    paint: wasm.six_paint,
    perforate: wasm.six_perforate,
    png: wasm.six_png,
    pro: wasm.six_pro,
    pro_design: wasm.six_pro_design,
    radial: wasm.six_radial,
    radial_crop: wasm.six_radial_crop,
    radial_mask: wasm.six_radial_mask,
    raster: wasm.six_raster,
    rect_png: wasm.six_rect_png,
    rect_svg: wasm.six_rect_svg,
    rim_holes: wasm.six_rim_holes,
    skin: wasm.six_skin,
    slice_core_graph: wasm.six_slice_core_graph,
    slice_dual_graph: wasm.six_slice_dual_graph,
    slice_edge_graph: wasm.six_slice_edge_graph,
    slice_tunnel_graph: wasm.six_slice_tunnel_graph,
    south: wasm.six_south,
    spectral_exponent: wasm.six_spectral_exponent,
    svg: wasm.six_svg,
    tessellate: wasm.six_tessellate,
    tile: wasm.six_tile,
    tile_cell: wasm.six_tile_cell,
    tile_crop: wasm.six_tile_crop,
    tile_step: wasm.six_tile_step,
    to_json: wasm.six_to_json,
    triangles: wasm.six_triangles,
    west: wasm.six_west,
    width: wasm.six_width,
    star: {
        Branch: wasm.six_star_Branch,
        Share: wasm.six_star_Share,
        Star: wasm.six_star_Star,
        arm_law: wasm.six_star_arm_law,
        chi8: wasm.six_star_chi8,
        constant: wasm.six_star_constant,
        decay: wasm.six_star_decay,
        width_law: wasm.six_star_width_law,
    },
};
export const spectrum = {
    clusters: wasm.spectrum_clusters,
    laplacian: wasm.spectrum_laplacian,
    laplacian_spectrum: wasm.spectrum_laplacian_spectrum,
    multiplicity: wasm.spectrum_multiplicity,
    spectral_exponent: wasm.spectrum_spectral_exponent,
    spectral_fit: wasm.spectrum_spectral_fit,
    spectral_points: wasm.spectrum_spectral_points,
    symmetric_eigenvalues: wasm.spectrum_symmetric_eigenvalues,
};
export const spin = {
    Blend: wasm.spin_Blend,
    arcs: wasm.spin_arcs,
    harmonics: wasm.spin_harmonics,
    mass: wasm.spin_mass,
    mass_within: wasm.spin_mass_within,
    petals: wasm.spin_petals,
    profile: wasm.spin_profile,
    radial: wasm.spin_radial,
    reach: wasm.spin_reach,
    ring: wasm.spin_ring,
    turns: wasm.spin_turns,
    wheel: wasm.spin_wheel,
};
export const spirograph = {
    LAPS_CAP: wasm.spirograph_LAPS_CAP,
    PENCIL_CAP: wasm.spirograph_PENCIL_CAP,
    POINT_CAP: wasm.spirograph_POINT_CAP,
    RADIUS_CAP: wasm.spirograph_RADIUS_CAP,
    RASTER_CAP: wasm.spirograph_RASTER_CAP,
    SIDES: wasm.spirograph_SIDES,
    cell: wasm.spirograph_cell,
    cover: wasm.spirograph_cover,
    disc: wasm.spirograph_disc,
    distinct: wasm.spirograph_distinct,
    frame: wasm.spirograph_frame,
    nodes: wasm.spirograph_nodes,
    pencils: wasm.spirograph_pencils,
    point: wasm.spirograph_point,
    pose: wasm.spirograph_pose,
    representatives: wasm.spirograph_representatives,
    seats: wasm.spirograph_seats,
    signed_area: wasm.spirograph_signed_area,
    trace: wasm.spirograph_trace,
    track: wasm.spirograph_track,
    turn: wasm.spirograph_turn,
};
export const three = {
    Vec3: wasm.three_Vec3,
    carpet: wasm.three_carpet,
    census: wasm.three_census,
    core_graph: wasm.three_core_graph,
    create: wasm.three_create,
    diagonal_slice: wasm.three_diagonal_slice,
    diagonal_svg: wasm.three_diagonal_svg,
    dust: wasm.three_dust,
    edge_graph: wasm.three_edge_graph,
    euler: wasm.three_euler,
    extrude: wasm.three_extrude,
    extrude_cube: wasm.three_extrude_cube,
    faces: wasm.three_faces,
    fills: wasm.three_fills,
    from_corners: wasm.three_from_corners,
    from_json: wasm.three_from_json,
    from_strings: wasm.three_from_strings,
    hidden: wasm.three_hidden,
    level_set: wasm.three_level_set,
    magic: wasm.three_magic,
    manhattan_layers: wasm.three_manhattan_layers,
    merge: wasm.three_merge,
    mosaic: wasm.three_mosaic,
    named: wasm.three_named,
    net: wasm.three_net,
    noise: wasm.three_noise,
    ones: wasm.three_ones,
    orientations: wasm.three_orientations,
    point: wasm.three_point,
    profile: wasm.three_profile,
    project: wasm.three_project,
    quads: wasm.three_quads,
    shadow: wasm.three_shadow,
    slice: wasm.three_slice,
    special: wasm.three_special,
    star: wasm.three_star,
    support: wasm.three_support,
    surface: wasm.three_surface,
    text: wasm.three_text,
    to_json: wasm.three_to_json,
    to_obj: wasm.three_to_obj,
    to_strings: wasm.three_to_strings,
    tunnel_graph: wasm.three_tunnel_graph,
    void: wasm.three_void,
    void_: wasm.three_void,
    voids: wasm.three_voids,
    volume: wasm.three_volume,
    wires: wasm.three_wires,
    xline: wasm.three_xline,
    xtree: wasm.three_xtree,
    yline: wasm.three_yline,
    ytree: wasm.three_ytree,
    zeros: wasm.three_zeros,
    zline: wasm.three_zline,
    ztree: wasm.three_ztree,
};
export const tourbillon = {
    eyes: wasm.tourbillon_eyes,
    field: wasm.tourbillon_field,
    layers: wasm.tourbillon_layers,
    period: wasm.tourbillon_period,
    sharing: wasm.tourbillon_sharing,
    stack: wasm.tourbillon_stack,
    stats: wasm.tourbillon_stats,
};
export const two = {
    capacity: wasm.two_capacity,
    carpet: wasm.two_carpet,
    census: wasm.two_census,
    create: wasm.two_create,
    dust: wasm.two_dust,
    embed: wasm.two_embed,
    euler: wasm.two_euler,
    extract: wasm.two_extract,
    fills: wasm.two_fills,
    from_corners: wasm.two_from_corners,
    from_json: wasm.two_from_json,
    from_strings: wasm.two_from_strings,
    hline: wasm.two_hline,
    htree: wasm.two_htree,
    level_set: wasm.two_level_set,
    mask: wasm.two_mask,
    merge: wasm.two_merge,
    named: wasm.two_named,
    net: wasm.two_net,
    noise: wasm.two_noise,
    ones: wasm.two_ones,
    perimeter: wasm.two_perimeter,
    png: wasm.two_png,
    point: wasm.two_point,
    read: wasm.two_read,
    sheet: wasm.two_sheet,
    special: wasm.two_special,
    star: wasm.two_star,
    svg: wasm.two_svg,
    text: wasm.two_text,
    to_3d: wasm.two_to_3d,
    to_json: wasm.two_to_json,
    vline: wasm.two_vline,
    void: wasm.two_void,
    void_: wasm.two_void,
    voids: wasm.two_voids,
    vtree: wasm.two_vtree,
    zeros: wasm.two_zeros,
    payload: {
        frame: wasm.two_payload_frame,
    },
};
