import * as wasm from "./pkg/num/mrlyjs_num.js";

export { default, initSync } from "./pkg/num/mrlyjs_num.js";
export const Rng = wasm.Rng;
export const apollonian = {
    CIRCLE_CAP: wasm.apollonian_CIRCLE_CAP,
    CURVATURE_CAP: wasm.apollonian_CURVATURE_CAP,
    Circle: wasm.apollonian_Circle,
    ORDER_CAP: wasm.apollonian_ORDER_CAP,
    ROOTS: wasm.apollonian_ROOTS,
    form: wasm.apollonian_form,
    frame: wasm.apollonian_frame,
    grow: wasm.apollonian_grow,
    is_ford: wasm.apollonian_is_ford,
    on_line: wasm.apollonian_on_line,
    reflect: wasm.apollonian_reflect,
    root: wasm.apollonian_root,
    shadow: wasm.apollonian_shadow,
    sound: wasm.apollonian_sound,
    swap: wasm.apollonian_swap,
    touches: wasm.apollonian_touches,
};
export const automaton = {
    Automaton: wasm.automaton_Automaton,
    ROUNDING: wasm.automaton_ROUNDING,
};
export const blend = {
    add: wasm.blend_add,
    cauchy: wasm.blend_cauchy,
    characteristic: wasm.blend_characteristic,
    decimate: wasm.blend_decimate,
    delta: wasm.blend_delta,
    growth: wasm.blend_growth,
    hadamard: wasm.blend_hadamard,
    recurrence: wasm.blend_recurrence,
    scale: wasm.blend_scale,
    shift: wasm.blend_shift,
    sigma: wasm.blend_sigma,
    sub: wasm.blend_sub,
};
export const boolean = {
    is_balanced: wasm.boolean_is_balanced,
    nonlinearity: wasm.boolean_nonlinearity,
    sac: wasm.boolean_sac,
    walsh_spectrum: wasm.boolean_walsh_spectrum,
};
export const design = {
    ZETA_ORDINATES: wasm.design_ZETA_ORDINATES,
    digits_of: wasm.design_digits_of,
    echo_series: wasm.design_echo_series,
    elements: wasm.design_elements,
    log_grid: wasm.design_log_grid,
    median_floor: wasm.design_median_floor,
    meter: wasm.design_meter,
    nearest: wasm.design_nearest,
    peaks: wasm.design_peaks,
    pole_lattice: wasm.design_pole_lattice,
    resample: wasm.design_resample,
    score: wasm.design_score,
    size: wasm.design_size,
    spectrum: wasm.design_spectrum,
    upper_rms: wasm.design_upper_rms,
};
export const factor = {
    aliquot: wasm.factor_aliquot,
    coprime: wasm.factor_coprime,
    divisors: wasm.factor_divisors,
    factorial: wasm.factor_factorial,
    factorize: wasm.factor_factorize,
    factorize_wide: wasm.factor_factorize_wide,
    gcd: wasm.factor_gcd,
    lcm: wasm.factor_lcm,
    mobius: wasm.factor_mobius,
    mobius_sieve: wasm.factor_mobius_sieve,
    radical: wasm.factor_radical,
    reduce: wasm.factor_reduce,
    sigma: wasm.factor_sigma,
    squarefree: wasm.factor_squarefree,
    totient: wasm.factor_totient,
    totients: wasm.factor_totients,
    twisted: wasm.factor_twisted,
};
export const fft = {
    convolve: wasm.fft_convolve,
    convolve_with: wasm.fft_convolve_with,
    embed_kernel: wasm.fft_embed_kernel,
    log_spectrum: wasm.fft_log_spectrum,
    magnitude_spectrum: wasm.fft_magnitude_spectrum,
    peak_ring: wasm.fft_peak_ring,
    peak_wavelength: wasm.fft_peak_wavelength,
    radial_profile: wasm.fft_radial_profile,
    transform: wasm.fft_transform,
};
export const gauss = {
    Class: wasm.gauss_Class,
    Ring: wasm.gauss_Ring,
    Window: wasm.gauss_Window,
    classes: wasm.gauss_classes,
    peak: wasm.gauss_peak,
    shells: wasm.gauss_shells,
};
export const ladder = {
    Design: wasm.ladder_Design,
    ROUNDING: wasm.ladder_ROUNDING,
    cofactor: wasm.ladder_cofactor,
    residue: wasm.ladder_residue,
    zeta: wasm.ladder_zeta,
};
export const lattice = {
    coprime_pairs: wasm.lattice_coprime_pairs,
    farey: wasm.lattice_farey,
    grid: wasm.lattice_grid,
    new_nodes: wasm.lattice_new_nodes,
    pi_estimate: wasm.lattice_pi_estimate,
    recovered: wasm.lattice_recovered,
    visible_density: wasm.lattice_visible_density,
    zeta_factor: wasm.lattice_zeta_factor,
    zeta_whole: wasm.lattice_zeta_whole,
};
export const memory = {
    Rule: wasm.memory_Rule,
    SPAN: wasm.memory_SPAN,
    SWEEPS: wasm.memory_SWEEPS,
    TOLERANCE: wasm.memory_TOLERANCE,
    allowed_windows: wasm.memory_allowed_windows,
    cells: wasm.memory_cells,
    counts: wasm.memory_counts,
    exponent: wasm.memory_exponent,
    kappa: wasm.memory_kappa,
    perron: wasm.memory_perron,
    transfer: wasm.memory_transfer,
};
export const morse = {
    LIFTS: wasm.morse_LIFTS,
    Lift: wasm.morse_Lift,
    boundary: wasm.morse_boundary,
    difference: wasm.morse_difference,
    digits: wasm.morse_digits,
    doubling: wasm.morse_doubling,
    faults: wasm.morse_faults,
    fold: wasm.morse_fold,
    letter: wasm.morse_letter,
    lift: wasm.morse_lift,
    power: wasm.morse_power,
    repeat: wasm.morse_repeat,
    runs: wasm.morse_runs,
    stage: wasm.morse_stage,
    substitution: wasm.morse_substitution,
    upsample: wasm.morse_upsample,
};
export const prime = {
    Sieve: wasm.prime_Sieve,
    chart: wasm.prime_chart,
    flags: wasm.prime_flags,
    goldbach: wasm.prime_goldbach,
    goldbach_record: wasm.prime_goldbach_record,
    is_prime: wasm.prime_is_prime,
    pile: wasm.prime_pile,
    prime_count: wasm.prime_prime_count,
    prime_from: wasm.prime_prime_from,
    primes: wasm.prime_primes,
    rectangles: wasm.prime_rectangles,
    splits: wasm.prime_splits,
    squares: wasm.prime_squares,
    study: wasm.prime_study,
};
export const radix = {
    Base: wasm.radix_Base,
    Radix: wasm.radix_Radix,
    flowsnake: wasm.radix_flowsnake,
    gasket: wasm.radix_gasket,
    koch: wasm.radix_koch,
    terdragon: wasm.radix_terdragon,
    tile: wasm.radix_tile,
    twindragon: wasm.radix_twindragon,
};
export const series = {
    APERY: wasm.series_APERY,
    BASEL: wasm.series_BASEL,
    CATALAN: wasm.series_CATALAN,
    EULER: wasm.series_EULER,
    VISIBLE: wasm.series_VISIBLE,
    basel: wasm.series_basel,
    bernoulli: wasm.series_bernoulli,
    beta: wasm.series_beta,
    binary: wasm.series_binary,
    catalan: wasm.series_catalan,
    chi3: wasm.series_chi3,
    chi4: wasm.series_chi4,
    chi8: wasm.series_chi8,
    dirichlet: wasm.series_dirichlet,
    e_partial: wasm.series_e_partial,
    euler_gamma_partial: wasm.series_euler_gamma_partial,
    euler_product: wasm.series_euler_product,
    evens: wasm.series_evens,
    fibonacci: wasm.series_fibonacci,
    harmonic: wasm.series_harmonic,
    lambda: wasm.series_lambda,
    leibniz: wasm.series_leibniz,
    li: wasm.series_li,
    mertens: wasm.series_mertens,
    odds: wasm.series_odds,
    visible: wasm.series_visible,
    wallis_half_pi: wasm.series_wallis_half_pi,
    wallis_quarter_pi: wasm.series_wallis_quarter_pi,
    zeta: wasm.series_zeta,
};
export const sieve = {
    PLANE_LIMIT: wasm.sieve_PLANE_LIMIT,
    cells: wasm.sieve_cells,
    exponent: wasm.sieve_exponent,
    flat_word: wasm.sieve_flat_word,
    holes: wasm.sieve_holes,
    limit: wasm.sieve_limit,
    odd_word: wasm.sieve_odd_word,
    punctures: wasm.sieve_punctures,
    raster: wasm.sieve_raster,
    ratio: wasm.sieve_ratio,
    side: wasm.sieve_side,
    solid_limit: wasm.sieve_solid_limit,
};
export const spiral = {
    Growth: wasm.spiral_Growth,
    Lattice: wasm.spiral_Lattice,
    Mark: wasm.spiral_Mark,
    diagonal: wasm.spiral_diagonal,
    level_of: wasm.spiral_level_of,
    marks: wasm.spiral_marks,
    snail: wasm.spiral_snail,
};
export const zeta = {
    Complex: wasm.zeta_Complex,
    JOIN: wasm.zeta_JOIN,
    Line: wasm.zeta_Line,
    bump: wasm.zeta_bump,
    corrections: wasm.zeta_corrections,
    kernel: wasm.zeta_kernel,
    mellin: wasm.zeta_mellin,
    novelty_main: wasm.zeta_novelty_main,
    novelty_wave: wasm.zeta_novelty_wave,
    psi_formula: wasm.zeta_psi_formula,
    psi_stair: wasm.zeta_psi_stair,
    raise: wasm.zeta_raise,
    sharp_novelty: wasm.zeta_sharp_novelty,
    smoothed_novelty: wasm.zeta_smoothed_novelty,
};
