import os
import re
import subprocess
from config import ROOT

OUTPUT = os.path.join(ROOT, "STATS.md")

LANGUAGES = {
    ".rs": "rust",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".py": "python",
    ".md": "markdown",
    ".json": "json",
    ".toml": "toml",
    ".css": "css",
    ".wgsl": "wgsl",
    ".c": "c",
    ".html": "html",
    ".js": "javascript",
    ".sh": "shell",
}

def generated(path):
    if path.startswith("sites/web/fixtures/"):
        return True
    if path == "pkgs/rs/mrlyfont/assets/MrlyFont.json":
        return True
    if path.endswith(".lock"):
        return True
    return False

def tracked():
    out = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT, capture_output=True, text=True)
    return [p for p in out.stdout.split("\0") if p and not generated(p) and os.path.exists(os.path.join(ROOT, p))]

def line_count(path):
    with open(os.path.join(ROOT, path), errors="ignore") as f:
        return len(f.read().splitlines())

def languages(paths):
    stats = {}
    for path in paths:
        ext = os.path.splitext(path)[1]
        lang = LANGUAGES.get(ext)
        if not lang:
            continue
        files, lines = stats.get(lang, (0, 0))
        stats[lang] = (files + 1, lines + line_count(path))
    rows = sorted(stats.items(), key=lambda kv: (-kv[1][1], kv[0]))
    lines = ["| language | files | lines |", "|---|---|---|"]
    for lang, (f, n) in rows:
        lines.append(f"| {lang} | {f} | {n} |")
    total_f = sum(f for f, _ in stats.values())
    total_n = sum(n for _, n in stats.values())
    lines.append(f"| total | {total_f} | {total_n} |")
    return lines

def tests(paths):
    rust = 0
    python = 0
    for path in paths:
        if path.endswith(".rs"):
            with open(os.path.join(ROOT, path), errors="ignore") as f:
                rust += f.read().count("#[test]")
        elif path.startswith("pkgs/py/web/tests") and path.endswith(".py"):
            with open(os.path.join(ROOT, path), errors="ignore") as f:
                python += f.read().count("def test_")
    return ["| language | tests |", "|---|---|", f"| rust | {rust} |", f"| python | {python} |"]

def activity():
    out = subprocess.run(
        ["git", "log", "-10", "--format=%x00%cs|%s", "--shortstat"],
        cwd=ROOT, capture_output=True, text=True,
    )
    lines = ["| commit | date | files | added | removed |", "|---|---|---|---|---|"]
    for chunk in out.stdout.split("\0"):
        if not chunk.strip():
            continue
        head, _, tail = chunk.partition("\n")
        date, subject = head.split("|", 1)
        subject = subject.replace("|", "\\|")
        files = added = removed = 0
        m = re.search(r"(\d+) files? changed", tail)
        if m:
            files = int(m.group(1))
        m = re.search(r"(\d+) insertions?\(\+\)", tail)
        if m:
            added = int(m.group(1))
        m = re.search(r"(\d+) deletions?\(-\)", tail)
        if m:
            removed = int(m.group(1))
        lines.append(f"| {subject} | {date} | {files} | {added} | {removed} |")
    return lines

def generate():
    paths = tracked()
    content = "# MrlyStats\n\nRegenerated by utils/stats.py on every gate.\n"
    content += "\n## Languages\n\n" + "\n".join(languages(paths)) + "\n"
    content += "\n## Tests\n\n" + "\n".join(tests(paths)) + "\n"
    content += "\n## Activity\n\n" + "\n".join(activity()) + "\n"
    with open(OUTPUT, "w") as f:
        f.write(content)
    print(f"Wrote {OUTPUT}")

if __name__ == "__main__":
    generate()
