[package]
name = "mrlycli"
version.workspace = true
edition.workspace = true

[dependencies]
libc = "0.2"
mrlycore = { path = "../../pkgs/mrlyrs/mrlycore" }
mrlyui = { path = "../../pkgs/mrlyrs/mrlyui" }
mrlyweb = { path = "../../pkgs/mrlyrs/mrlyweb" }
mrlyos = { path = "../../pkgs/mrlyrs/mrlyos" }
